### Get a list of all products
GET http://localhost:3000/products


### Create a product

POST http://localhost:3000/products
Content-Type: application/json

{
    "name": "Apple Watch",
}


### GET a product by id
GET http://localhost:3000/products/6077eab25cfd8c361408fe7e


### Update a product by id
PATCH  http://localhost:3000/products/6077ed51741a681e24aa7d90
Content-Type: application/json

{
    "price": 1249
}


### Delete a product by id
DELETE  http://localhost:3000/products/6077eab25cfd8c361408fe7e


### 404 route Not Found 
GET http://localhost:3000/abc_xyz


###
GET http://localhost:3000/test?name=iMac&price=2399



###
GET http://localhost:3000/test/55555555555/imac


###
POST http://localhost:3000/test
Content-Type: application/json

{
    "name": "iMacPro",
    "price": 4999
}


###
POST http://localhost:3000/test
Content-Type: application/x-www-form-urlencoded

name=iMac&price=499